### ISSUE TITLE
Index page issue

### ISSUE THREAD

**Issue by walkerz88** [EmmanuelBeziat/emmanuelbeziat#11]
Hi! If i update index page of your site several times, i can get ___PHP0___ in main block. Please see screenshot
![2018-02-07 15 09 12](https://user-images.githubusercontent.com/18183967/35915775-2c5ef57a-0c19-11e8-84d6-4250e2f9fb18.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

And a background issue, I see… Thanks for that.
