### ISSUE TITLE
Social share and github pages

### ISSUE THREAD

**Issue by EmmanuelBeziat** [EmmanuelBeziat/emmanuelbeziat#8]
As I'm using the "404 hack ([sghpa](https://github.com/csuwildcat/sghpa))" to have custom routes using gh-pages.

But when sharing an article, it reach this 404 file, and thus don't get all the opengraph meta and stuff, that are called / generated after.

**Comment by EmmanuelBeziat** [comment]
@reverland if by any chance you have an idea on this? 😄

**Comment by reverland** [comment]
sorry, I dont, so does for google to crawl...

maybe its better to host the pages in our own servers

**Comment by EmmanuelBeziat** [comment]
Thought about it too, yeah. That’s disappointing from github… Understandable, but disappointing.

**Comment by EmmanuelBeziat** [comment]
@reverland I just switched the site on my own server. I’ll let you know if there are any changes in Google and Facebook.

**Comment by reverland** [comment]
@EmmanuelBeziat vue announced its 2.0 version, it looks like it have a well support for server side rendering, so, maybe 404 hack may not be necessary?

**Comment by EmmanuelBeziat** [comment]
Yeah, I think it might be better to switch. But it's not that easy to make. I'm trying, though.

**Comment by reverland** [comment]
I've considered use webpack and vue2 to rebuild the blog utilities for a LONG LONG LONG LONG LONG LONG LONG time.

Your site looks really FANTASTIC(Though I can't really understand your language...)! I'm even consider fork your site, reuse these styles and parts of the views or components(what you put in `/components` or `modules`).

Though we may have different needs, I hope we can write things in well decoupled components, register what we need when necessary. In this way we can save more time and energy and more easily extend site by needs.

Hope all us explorable work can be better organized to provide a flexible plugin/component/view system with reasonable default configuration.

So one can use it out-of-box to build static site that he need, and extend it freely with other people's  work without reinvent wheels.

Just an Imagination, I may never have time or energy to do this, but it is how I hope my site looks in the future. hahaha~ poor english, sorry for that

**Comment by EmmanuelBeziat** [comment]
Honestly, when I found your project I was doing something similar for 2 month, but I dropped it because yours was way better. Most of the vue system i came up with is a fork of yours. I learned a lot by looking at your code. So, if you fork it, you will basically fork a fork of your site core. 😄 But if you like the views, feel free to use them, i'm totally ok with that!

I'm working (slowly) on a v2 (with vue2), but i'm way more efficient with integration and front-js. It may take me some time to build something usable. And I'm not sure I could produce something flexible enough to be an out-of-box system. I'll try though. I'll let you know how things are going.

> Your site looks really FANTASTIC(Though I can't really understand your language...)!

Thanks! I like your site too, even if I'm more confident with using my own CSS stuff instead of a framework. The result on your site is really clean, and it made me discover semantic-ui, that I actually used on a recent pro work to give it a try (I'm really sick of bootstrap).

Same for me, i don't know a single character of Chinese. But I've read all I could found in english. Your post about webpack helped me a lot some month ago, actually. It was really helpful to me, to get a better understanding of what I was doing (and how you used it on your website).

> poor english, sorry for that

I didn't see anything wrong in your english (though I'm not english myself). :)

**Comment by EmmanuelBeziat** [comment]
@reverland I think this may be what we missed here. https://github.com/chrisvfritz/prerender-spa-plugin The point is to "prerender" the app. But this require to add the existing url in Webpack. So I think we need to crawl the post's json to add every single post url to it before the build.

I'll let you know what I came up with.

**Comment by reverland** [comment]
Maybe the problem is how to add webpack config on the fly.. it looks like one can implement a plugin inject webpack config for prerender,

Last but not least, prerender may be slow... I don't like a static blog generator such slow

**Comment by EmmanuelBeziat** [comment]
Agreed. I’ll check if the build time get heavily impacted.

**Comment by EmmanuelBeziat** [comment]
Now using a full static generated website, it's working. :)
